server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        proxy_pass http://backend:8000/static/;
    }

    location /media/ {
        proxy_pass http://backend:8000/media/;
    }


    location /api/ {
        proxy_pass http://backend:8000/api/;
    }


    location /weather/ {
        proxy_pass http://backend:8000/weather/;
    }

    location /news/ {
        proxy_pass http://backend:8000/news/;
    }
}
