services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather_net


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    ports:
      - "8022:8000"
    volumes:
      - media_volume:/app/backend/media
      - static_volume:/app/backend/staticfiles
    networks:
      - weather_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_OPENWEATHERMAP_API_KEY=${VITE_OPENWEATHERMAP_API_KEY}
      - VITE_STATIC_BASE_URL=/static 
      - VITE_WEATHER_API_BASE_URL=/api/v1/weather
      - VITE_USER_API_BASE_URL=/api/v1/user
    ports:
      - "85:80"
    volumes:
      - media_volume:/usr/share/nginx/html/media
      - static_volume:/usr/share/nginx/html/static
    networks:
      - weather_net

networks:
  weather_net:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: