services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5433:5432"
    networks:
      - weather_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: config.settings.prod
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DATABASE_URL: ${DATABASE_URL}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      OPENWEATHERMAP_API_KEY: ${OPENWEATHERMAP_API_KEY}
      NEWS_API_KEY: ${NEWS_API_KEY}
    ports:
      - "8022:8000"
    depends_on:
      - db
    networks:
      - weather_net
    volumes:
      - media_volume:/app/backend/media               # ✅ Shared media volume
      - static_volume:/app/backend/staticfiles        # ✅ Shared static volume

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_OPENWEATHERMAP_API_KEY: ${VITE_OPENWEATHERMAP_API_KEY}
    ports:
      - "85:80"
    networks:
      - weather_net
    depends_on:
      - backend
    volumes:
      - media_volume:/media                           # ✅ Same media volume as backend
      - static_volume:/usr/share/nginx/html/static    # ✅ Same static volume as backend

networks:
  weather_net:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
