FROM python:3.10-slim AS backend-build

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings.prod

WORKDIR /app/backend

COPY backend/requirements /app/backend/requirements

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libffi-dev \
    libssl-dev \
    && pip install --upgrade pip setuptools wheel

RUN pip install -r requirements/prod.txt

COPY backend/ .

EXPOSE 8000

# Custom entrypoint script to collect static and run gunicorn
CMD ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"]
