# -------- USER ---------

### Register User
POST http://127.0.0.1:8000/api/v1/user/register/
Content-Type: application/json

{
  "username": "trnc",
  "password": "password123",
  "email": "terence7ds@gmail.com",
  "location": "Berlin",
  "preferred_temperature_unit": "C"
}

### Login User
POST http://127.0.0.1:8000/api/v1/user/login/
Content-Type: application/json

{
    "username": "trnc",
    "password": "password123"
}

### Logout User
POST http://127.0.0.1:8000/api/v1/user/logout/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351


### User Profile
GET http://127.0.0.1:8000/api/v1/user/profile/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351

### Edit User Profile

PUT http://127.0.0.1:8000/api/v1/user/profile/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351

{
    "email": "terence7ds@gmail.com",
    "first_name": "Terence",
    "last_name": "Tahalele",
    "username": "trnc",
    "location": "Berlin",
    "preferred_temperature_unit": "C"
}

# -------- WEATHER ---------

### Get Current Weather
GET http://127.0.0.1:8000/api/v1/weather/current/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351


### Get Favorite Locations Weather
GET http://127.0.0.1:8000/api/v1/weather/favorites/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351


### Get Weather Forecast
GET http://127.0.0.1:8000/api/v1/weather/forecast/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351


### Get Weather Radar Data
GET http://127.0.0.1:8000/api/v1/weather/alerts/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351


### Get Weather News
GET http://127.0.0.1:8000/api/v1/weather/news/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351


### Get Weather Radar Data
GET http://127.0.0.1:8000/api/v1/weather/radar/
Content-Type: application/json
Authorization: Token aa44f90382bdabc6be2d821235b4eb468859d351

