# Generated by Django 5.0.6 on 2024-08-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_current"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField()),
                ("max_temperature", models.FloatField()),
                ("min_temperature", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("weather_description", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.location",
                    ),
                ),
            ],
        ),
    ]
