# Generated by Django 5.0.6 on 2025-02-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_favoritelocation_alter_current_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Current',
        ),
    ]
