# Generated by Django 5.0.6 on 2025-02-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_delete_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
